name: Scheduled Backup to S3

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    uses: akerotwo/github-actions-workflows/.github/workflows/backup-to-s3.yml@main
    with:
      ref: main
      s3_prefix: scheduled
    secrets: inherit

